django/tango_with_django_project_1to11chapter/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^add_category/$',views.add_category,name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',views.add_page,name='add_page'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^restricted/$',views.restricted,name='restricted'),
]

django/tango_with_django_project_1to11chapter/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,user):
        return '/rango/'



urlpatterns = [
    url(r'^rango/',include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',MyRegistrationView.as_view(),name='registration_register'),
    url(r'^accounts/',include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django/tango_with_django_project_1to11chapter/rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images',blank=True)

    def __unicode__(self):
        return self.user.username

django/tango_with_django_project_1to11chapter/rango/forms.py
from django import forms
from rango.models import Page,Category,UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)
    
    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text='please enter the title of the page.')
    url = forms.URLField(max_length=200,help_text="please enter the url of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture')

django/tango_with_django_project_1to11chapter/rango/views.py
# -*- encoding:utf-8 -*-

from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse

from rango.models import Category,Page
from rango.forms import CategoryForm,PageForm,UserForm,UserProfileForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect , HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

@login_required
def restricted(request):
    return render(request,'rango/restricted.html',{})

def index(request):

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories':category_list,'pages':page_list}
 
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
   
    response = render(request,'rango/index.html',context_dict)

    return response

def about(request):
    return HttpResponse("<h1>this is about page!</h1>")

def show_category(request,category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request,'rango/category.html',context_dict) 

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
        
    return render(request,'rango/add_category.html',{'form':form})

@login_required
def add_page(request,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request,category_name_slug)
        else:
            print(form.errors) 

    context_dict = {'form':form,'category':category}
    return render(request,'rango/add_page.html',context_dict)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
   
            profile.save()

            registered = True
 
        else:
            print(user_form.errors , profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request,
                  'rango/register.html',
                  {'user_form':user_form,'profile_form':profile_form,'registered':registered}
                 )


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse("your rango account is disabled.")
        else:
           print("invalid login details: {0} , {1}".format(username,password))
           return HttpResponse("invalid login details supplied.")

    else:
        return render(request,'rango/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_server_side_cookie(request,cookie,default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 4:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        #visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

django/tango_with_django_project_1to11chapter/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    add category
{% endblock %}

{% block body_block %}
        <h1>add a category</h1>
        <div>
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="create category">
            </form>
        </div>
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    add page for {{ category.name }}
{% endblock %}

{% block body_block %}
        <strong><h1>add a apge to category</h1></strong>
        <div>
            <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="add page" />
            </form>
        </div>
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <title>
            Rango -
            {% block title_block %}
                How to tango with django
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <hr />
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted page</a></li>
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">add new category</a></li>
                {% else %}
                    <li><a href="{% url 'auth_login' %}">Sign In</a></li>
                    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">about</a></li>
                <li><a href="{% url 'rango:index' %}">index</a></li>
            </ul>    
        </div>
    </body>
</html>

django/tango_with_django_project_1to11chapter/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
        <div>
            {% if category %}
                <h1>{{ category.name }}</h1>
                {% if pages %}
                    <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages current in category.</strong>
                {% endif %}
            {% else %}
                The specified category does not exist!
            {% endif %}
        </div>
        <div>
            {% if user.is_authenticated %}
                {% if category %}
                    <a href="{% url 'rango:add_page' category.slug %}">add page</a><br />
                {% endif %}
            {% endif %}
            <strong><a href="{% url 'rango:index' %}">return back to index page</a></strong>
        </div>
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/cats.html
<ul>
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <strong><li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li></strong>
        {% else %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>there are no categories present</strong></li>
{% endif %}
</ul>

django/tango_with_django_project_1to11chapter/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    index
{% endblock %}

{% block body_block %}
     <p>visits:{{ visits }}</p>
     <h1>Rango says</h1>
        <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}
        {% else %}
            hey there partner!
        {% endif %}
        </div>
        <div>
            <strong>most liked categories</strong>
            {% if categories %}
                <ul>
                    {% for category in categories %}
                        <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present</strong>
            {% endif %}
            <strong>most viewed pages</strong>
            {% if pages %}
                <ul>
                    {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no page present</strong>
            {% endif %}
        </div>
        <div>
            <a href="{% url 'rango:add_category' %}">add a new category</a><br />
            <img src="{% static "images/rango.jpg" %}" alt="Picture Rango" />
        </div>
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    login
{% endblock %}

{% block body_block %}
    <h1>login to rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    username: <input type="text" name="username" value="" size="50" />
    password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
    </form>
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage</a>
    {% else %}
        Rango says: <strong>register here!</strong>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

django/tango_with_django_project_1to11chapter/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    restricted
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}