django/xcmdb/xcmdb/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^xcmdb/',include('xcmdb_main.urls')),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django/xcmdb/xcmdb_main/urls.py
from django.conf.urls import url
from xcmdb_main import views

app_name = "xcmdb_main"

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^login/$',views.auth_login,name="auth_login"),
    url(r'^logout/$',views.auth_logout,name="auth_logout"),
    url(r'^sum/$',views.global_sum,name="global_sum"),
    url(r'^add_host/$',views.add_host,name="add_host"),
    url(r'^manage_host/$',views.manage_host,name="manage_host"),
    url(r'^query/$',views.query_service,name="query_service"),
    url(r'^exec_job/$',views.exec_job,name="exec_job"),
    url(r'^help/$',views.help_service,name="help_service"),
]

django/xcmdb/xcmdb_main/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class MachineRoomInfo(models.Model):

    machine_room = models.CharField(max_length=10,unique=True)

    def __unicode__(self):
        return self.machine_room

class HostEnvCategory(models.Model):

    hostenv = models.CharField(max_length=5,unique=True)

    def __unicode__(self):
        return self.hostenv

class HostBusiSysCate(models.Model):

    business_sys_category = models.CharField(max_length=30,unique=True)

    def __unicode__(self):
        return self.business_sys_category

class AppCategory(models.Model):
    
    app_category = models.CharField(max_length=15,unique=True)

    def __unicode__(self):
        return self.app_category


class HostBaseInfo(models.Model):

    hostname = models.SlugField(max_length=30,unique=True)
    hostenv = models.CharField(max_length=5)
    business_sys_category = models.CharField(max_length=30)
    app_category = models.CharField(max_length=15)
    app_port = models.CharField(max_length=15)

    machine_room = models.CharField(max_length=5)
    phy_machine_flag = models.CharField(max_length=50,blank=True)

    owner = models.CharField(max_length=15)

    os = models.CharField(max_length=10)
    machine_type = models.CharField(max_length=10)

    account = models.CharField(max_length=15,blank=True)
    password = models.CharField(max_length=100,blank=True)

    create_time = models.DateField()
    remark = models.CharField(max_length=100,blank=True)
    

    def __unicode__(self):
        return self.hostname


class HostGroupInfo(models.Model):

    groupname = models.SlugField(max_length=30,unique=True)
    remark = models.CharField(max_length=50,blank=True)

    def __unicode__(self):
        return self.groupname


class HostMapGroup(models.Model):

    hostbaseinfo = models.ForeignKey(HostBaseInfo)
    groupid = models.IntegerField()

    def __unicode__(self):
        return hostbaseinfo.hostname


class HostIPInfo(models.Model):

    hostbaseinfo = models.ForeignKey(HostBaseInfo)
    ncname = models.CharField(max_length=15)
    ncip = models.GenericIPAddressField()

    def __unicode__(self):
        return hostbaseinfo.hostname

django/xcmdb/xcmdb_main/forms.py
#-*- encoding:utf-8 -*-

from django import forms
from datetime import datetime
from xcmdb_main.models import HostBaseInfo,MachineRoomInfo,HostEnvCategory,HostBusiSysCate,AppCategory


class AddHostForm(forms.ModelForm):

    hostname = forms.SlugField(max_length=30,help_text=u'主机名:')
    hostenv = forms.ModelChoiceField(queryset=HostEnvCategory.objects.all(),help_text=u'所属环境:')
    business_sys_category = forms.ModelChoiceField(queryset=HostBusiSysCate.objects.all(),help_text=u'所属业务:')
    app_category = forms.ModelChoiceField(queryset=AppCategory.objects.all(),help_text=u'应用类型:')
    app_port = forms.CharField(max_length=15,help_text=u'应用端口:')


    machine_room = forms.ModelChoiceField(queryset=MachineRoomInfo.objects.all(),help_text=u'机房:')

    phy_machine_flag = forms.CharField(max_length=50,required=False,help_text=u'机器位置:')

    owner = forms.CharField(max_length=15,help_text=u'拥有者:')
    account = forms.CharField(max_length=15,help_text=u'账号:')
    password = forms.CharField(max_length=100,help_text=u'密码:')

    create_time = forms.DateField(initial=datetime.now().strftime("%Y-%m-%d"),help_text=u'主机创建时间:')
    
    remark = forms.CharField(widget=forms.Textarea,required=False,help_text=u"备注:")

    class Meta:
        model = HostBaseInfo
        exclude = ['os','machine_type',]
    

django/xcmdb/xcmdb_main/views.py
from django.shortcuts import render
from xcmdb_main.forms import AddHostForm


def index(request):

	response = render(request,'xcmdb_main/index.html',{})
	return response


def auth_login(request):
	pass


def auth_logout(request):
	pass


def global_sum(request):
	pass


def add_host(request):
	form = AddHostForm()

	if request.method == 'POST':
		print request.POST

	return render(request,'xcmdb_main/add_host.html',{'form':form})


def manage_host(request):
	pass


def query_service(request):
	pass


def exec_job(request):
	pass


def help_service(request):
	pass

django/xcmdb/templates/xcmdb_main/add_host.html
{% extends 'xcmdb_main/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
    addhost
{% endblock %}

{% block extrahead_block %}

{% endblock %}

{% block body_block %}
	<form role="form" id="add_host_form" method="post" action="{% url 'xcmdb_main:add_host' %}">
	{% csrf_token %}
	{% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}

	<br/>

	<button class="btn btn-primary" type="submit" name="submit">ADD HOST</button>
	</form>
{% endblock %}

django/xcmdb/templates/xcmdb_main/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
	
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
	Xcmdb-
	{% block title_block %}
	{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css'%}" rel="stylesheet">
	
    </head>

    <body>
    
    <!-- PART ONE -->
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
	
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
	  
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
	  
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#"><img width="30" height="30" src="http://lorempixel.com/64/64/people/"/><a>
            </li>
        </ul>
		
        <div class="form-inline mt-2 mt-md-0">
			{% if user.is_authenticated %}
				<a href="{% url 'xcmdb_main:auth_logout'%}">Logout</a>
			{% else %}
				<a href="{% url 'xcmdb_main:auth_login'%}">Login</a>
			{% endif %}
	</div>
		
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
	  
	<!-- PART TWO -->
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
			{% block sidebar_block %}
			  <ul class="nav nav-pills flex-column">
				<li class="nav-item">
				  <a class="nav-link active" href="{% url 'xcmdb_main:global_sum' %}">全局概览</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="{% url 'xcmdb_main:add_host' %}">添加主机</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="{% url 'xcmdb_main:manage_host' %}">管理主机</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="{% url 'xcmdb_main:query_service' %}">查询服务</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="{% url 'xcmdb_main:exec_job' %}">作业执行</a>
				</li>			
			  </ul>
			  <hr>
			  <ul class="nav nav-pills flex-column">
				<li class="nav-item">
				  <a class="nav-link" href="{% url 'xcmdb_main:help_service' %}">帮助</a>
				</li>
			  </ul>
			{% endblock %}
        </nav>

		<!-- PART THREE -->
        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}
	        {% endblock %}
        </main>
		
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
	
    </body>
</html>

django/xcmdb/templates/xcmdb_main/index.html
{% extends 'xcmdb_main/base.html' %}
{% load staticfiles %}

{% block title_block %}
    index
{% endblock %}

{% block body_block %}
          <h2>主机统计</h2>
          <hr/>
          <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h5>全网Linux主机数</h5>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h5>全网widnows主机数</h5>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </section>

          <h2>作业统计</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
{% endblock %}