django/tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^add_category/$',views.add_category,name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',views.add_page,name='add_page'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^restricted/$',views.restricted,name='restricted'),
    url(r'^search/$',views.search,name='search'),
    url(r'^goto/$',views.track_url,name='goto'),
    url(r'^like/$',views.like_category,name='like_category'),
    url(r'^suggest/$',views.suggest_category,name='suggest_category'),
    url(r'^add/$',views.auto_add_page,name='auto_add_page'),
]

django/tango_with_django_project/rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

django/tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page,Category

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)
    
    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text='please enter the title of the page.')
    url = forms.URLField(max_length=200,help_text="please enter the url of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            
            return cleaned_data

django/tango_with_django_project/rango/views.py
# -*- encoding:utf-8 -*-

from datetime import datetime

from django.shortcuts import render,redirect
from django.http import HttpResponse

from rango.models import Category,Page
from rango.forms import CategoryForm,PageForm,UserForm,UserProfileForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect , HttpResponse
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

from rango.webhose_search import run_query

@login_required
def restricted(request):
    return render(request,'rango/restricted.html',{})

def index(request):

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories':category_list,'pages':page_list}
 
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
   
    response = render(request,'rango/index.html',context_dict)

    return response

def about(request):
    return HttpResponse("<h1>this is about page!</h1>")

def show_category(request,category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    context_dict['query'] = category.name
    
    result_list = []
    if request.method == "POST":
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
            context_dict['query'] = query
            context_dict['result_list'] = result_list
    
    return render(request,'rango/category.html',context_dict) 

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
        
    return render(request,'rango/add_category.html',{'form':form})

@login_required
def add_page(request,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request,category_name_slug)
        else:
            print(form.errors) 

    context_dict = {'form':form,'category':category}
    return render(request,'rango/add_page.html',context_dict)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
   
            profile.save()

            registered = True
 
        else:
            print(user_form.errors , profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request,
                  'rango/register.html',
                  {'user_form':user_form,'profile_form':profile_form,'registered':registered}
                 )


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse("your rango account is disabled.")
        else:
           print("invalid login details: {0} , {1}".format(username,password))
           return HttpResponse("invalid login details supplied.")

    else:
        return render(request,'rango/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_server_side_cookie(request,cookie,default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 4:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        #visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def search(request):
    result_list = []
    query = None
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request,'rango/search.html',{'result_list':result_list,'query_string':query})


def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == "GET":
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views = page.views + 1
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)

@login_required
def like_category(request):
    cat_id = None
    if request.method == "GET":
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()

        return HttpResponse(likes) 


def get_category_list(max_results=0,starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]

    return cat_list

def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == "GET":
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8,starts_with)
   
    return render(request,'rango/cats.html',{'cats':cat_list})


@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None

    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category=category,title=title,url=url)
            pages = Page.objects.filter(category=category).order_by('-views')
            context_dict['pages'] = pages        
    return render(request,'rango/page_list.html',context_dict)

django/tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
    add category
{% endblock %}

{% block body_block %}
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                <h2 class="form-signin-heading">Add a Category</h2>
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <br/>
                <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
            </form>
{% endblock %}

django/tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
    add page for {{ category.name }}
{% endblock %}

{% block body_block %}
            <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            <h2 class="form-signin-heading">add a apge to category</h2>
            {% csrf_token %}
            {{ form|as_bootstrap }}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
            </form>
{% endblock %}

django/tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    
    <title> Rango - {% block title_block %}how to rango with django{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     <!-- <a class="navbar-brand" href="{% url 'rango:index'%}">Rango</a> -->

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:search' %}">Search</a>
          </li>
		  {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
		  {% else %}
		  <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
		  <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          </li>
		  {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
		{% block sidebar_block %}
		    <!-- {% get_category_list category %} -->
                    <ul class="nav nav-list flex-column">
                        <li class="nav-item">Type to find a category</li>
                        <form>
                        <li class="nav-item">
                        <input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" />
                        </li>
                        </form>
                    </ul>
                    <hr>
                    <div id="cats">
                    </div>
		{% endblock %}
        </div>

        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
        {% block body_block %}
	{% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

django/tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
        <div>
            {% if category %}
                <h1>{{ category.name }}</h1>
                <div>
                    <strong id="like_count">{{ category.likes }}</strong> people like this category
                    {% if user.is_authenticated %}
                        <button id="likes" data-catid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                        Like
                        </button>
                    {% endif %}
                </div>
                {% if pages %}
                    <ul>
                    {% for page in pages %}
                        <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        {% if page.views > 1 %}
                            ({{ page.views }} views)
                        {% elif page.views == 1 %}
                            ({{ page.views }} view)
                        {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages current in category.</strong>
                {% endif %}
                
                <hr>
                <div id="pages">
                </div>

            {% else %}
                The specified category does not exist!
            {% endif %}
        </div>
        <div>
            {% if user.is_authenticated %}
                {% if category %}
                    <a href="{% url 'rango:add_page' category.slug %}">add page</a><br />
                    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                        </div>
                        <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
                    </form>
                    <div>
                        {% if result_list %}
                            <h3>Results</h3>
                            <div class="list-group">
                                {% for result in result_list %}
                                    <div class="list-group-item">
                                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                    <p class="list-group-item-text">{{ result.summary }}</p>
                                    <button data-catid="{{ category.id }}" data-title="{{ result.title }}" data-url="{{ result.link }}" class="rango-add btn btn-info btn-sm" type="button">
                                    Add
                                    </button>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
            <strong><a href="{% url 'rango:index' %}">return back to index page</a></strong>
        </div>
{% endblock %}

django/tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    index
{% endblock %}

{% block body_block %}
 
        <div class="jumbotron">
         <h1 class="display-3">Rango says...</h1>
         {% if user.is_authenticated %}
             <h1>hey there {{ user.username }}!</h1>
         {% else %}
             <h1>hey there partner!</h1>
         {% endif %}
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
            <h4>most liked categories</h4>
            <p>
            {% if categories %}
                <ul class="list-group">
                    {% for category in categories %}
                        <li class="list-group-item">
                           <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                           <span class="badge badge-pill badge-primary">{{ category.likes }}</span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present</strong>
            {% endif %}
            </p>
            </div>

            <div class="cpl-lg-6">
            <h4>most viewed pages</h4>
            <p>
            {% if pages %}
                <ul class="list-group">
                    {% for page in pages %}
                    <li class="list-group-item">
                        <a href="{{ page.url }}">{{ page.title }}</a>
                        <span class="badge badge-pill badge-primary">{{ page.views }}</span>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no page present</strong>
            {% endif %}
            </p>
            </div>
        </div>
        <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

django/tango_with_django_project/templates/rango/page_list.html
{% if pages %}
<ul>
    {% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a></li>
    {% endfor %}       
</ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

django/tango_with_django_project/templates/rango/profile_registration.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Registration - Step 2
{% endblock %}

{% block body_block %}
    <h1>Registration - Step 2</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" />
    </form>
{% endblock %}

django/tango_with_django_project/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}
    <div>
        <h1>Search with Rango</h1>
        <br />
        <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
            {% csrf_token %}
            <div class="form-group">
                {% if query_string %}
                  <input class="form-control" type="text" size=50 name="query" value="" placeholder="{{ query_string }}"  id="query"/>
                {% else %}
                  <input class="form-control" type="text" size=50 name="query" value="" id="query"/>
                {% endif %}
            </div>
            <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
        </form>
        <div>
            {% if result_list %}
                <h3>Results</h3>
                <div class="list-group">
                    {% for result in result_list %}
                        <div class="list-group-item">
                            <h5><a href="{{ result.link }}">{{ result.title }}</a></h5>
                            <p class="list-group-item-text">{{ result.summary }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}